### PR TITLE
UnderlinedTabItem with icon (Geometry and ImageIcon)

### PR DESCRIPTION
**Pull request by mkanyo**
This is an extension of `UnderlinedTabItem` - an implementation that has a bindable `public Geometry GeometryIcon` property where you can add a `PathGeometry` (or `GeometryGroup`) to set an SVG based icon. This is for the enhancement logged here: #13 

Because `UnderlinedTabItem` uses XAML it cannot be directly descended as the controls it declares in XAML are generated in the designer code and descending it causes naming crashes for variables. Therefore most of the (common) logic for the UnderlinedTabItem was moved to a base class `UnderlinedTabItemBase`.

I tested this locally incrementing the version to <Version>2.1.1</Version> and using it in a Xamarin Forms project as a local nuget.

This is how the `GeometryIconUnderlinedTabItem` can be used:

image

image

image

And the original `UnderlinedTabItem` also still works fine:

image

image

Let me know how you find it and if you need any other section in the code or docs updated.

### CODE REVIEW

**Comment by roubachof** [comment]
Nicely done so far :)
Would you care adding also `ImageIconUnderlinedTabItem` with an `ImageSource` property so we can have a global Image icon solution?

I'm quoting here @mgierlasinski in issue #13:
"It would be nice to have additional property, maybe IconImageSource (to be consistent with BottomTabItem) which will allow to set any ImageSource next to Label."

**Comment by mkanyo** [comment]
Sure, I'll have a look at that! 🤓

**Comment by mkanyo** [comment]
I added a new control `ImageIconUnderlinedTabItem` which has similar interface as `BottomTabItem`:

- `ImageSource IconImageSource`
- `double IconSize`
- `Color UnselectedIconColor`
- `bool IsTextVisible`

This is an example where I'm trying to use all properties:
image

Which renders:
image

image

Let me know if you need anything changed?

**Comment by mkanyo** [comment]
Just added another update that allows for the user of `GeometryIconUnderlinedTabItem` to specify if they want the `Geometry` shape `bool Fill` or drawn (if so with `double StrokeThickness`).

So now you can specify if you want the Shape filled:
image

Or drawn with the given thickness:
image

**Comment by mkanyo** [comment]
Hello @roubachof, have you any thoughts on the above? 😬

**Comment by mkanyo** [comment]
@roubachof just keeping tabs on this 🤓 so to speak. Do you have any comments/suggestions to improve?

**Comment by roubachof** [comment]
Yeah sorry I'm loaded with work... I hope I could merge those glorious awaiting PR soon.
Anyway I have a challenge for you.
There is in fact specs for underlined tabs with icons here : https://material.io/components/tabs#specs
Those tabs also support:
* Text or no text
* Icon or no Icon
* Leading or Top Icon
see here: https://material.io/components/tabs

Would you accept the challenge to fully implement those specs?
You will receive 20 sharpnado points for such a gesture.

For the implementation, it means that the image and the text should be put in a stack layout.
When you are switching from Leading to Top icon, you just change the stack orientation.

**Comment by mkanyo** [comment]
Challenge accepted! 🤓

**Comment by mkanyo** [comment]
Hello 

So, I updated `GeometryIconUnderlinedTabItem` with a new property `Orientation` which can have the following values:

- None: when this is specified the icon does not render
- Top: (default) this renders the icon on top of text
- Leading: this renders the icon leading left of the text
- IconOnly: this hides the text and only renders the icon

This shows an example of all variations:

`<tabs:TabHostView.Tabs>
    <tabs:GeometryIconUnderlinedTabItem
        GeometryIcon="{StaticResource SvgProfile}"
        IsSelected="True"
        Label="Profilom"
        Orientation="Leading"
        Style="{StaticResource TabStyle}" />
    <tabs:GeometryIconUnderlinedTabItem
        GeometryIcon="{StaticResource SvgEventCalendar}"
        Label="Események"
        Style="{StaticResource TabStyle}" />
    <tabs:GeometryIconUnderlinedTabItem
        GeometryIcon="{StaticResource SvgTastingGlass}"
        Label=""
        Orientation="IconOnly"
        Style="{StaticResource TabStyle}" />
    <tabs:GeometryIconUnderlinedTabItem
        Fill="True"
        GeometryIcon="{StaticResource SvgFavorites}"
        Label="Kedvencek"
        Orientation="None"
        StrokeThickness="1.0"
        Style="{StaticResource TabStyle}" />
</tabs:TabHostView.Tabs>`

This renders like this:
image

Is this approach OK?

Also, are you OK with my separate implementation for tabs with `ImageSource` images - currently called ImageIconUnderlinedTabItem? That and the Geometry based images require different input so I thought it better separate but I guess they could be merged into one that has support for both input (with one having to be dominant over the other).

Lastly but along the tracks of the last thought... I suppose we could also merge all functionality into the original `UnderlinedTabItem` too because if `Orientation = None` that's practically the original `UnderlinedTabItem`? 😀

**Comment by roubachof** [comment]
Now I think we should be closer proportion wise to the material tabs specs:

https://material.io/components/tabs#specs

in your example there is not enough space between the underline and the text, and too much between the label and the icon.
It should be more balanced.

Also, do we need to set the label to an empty string if we set IconOptions to IconOnly?

For the implementation, I think we should leave the current UnderlinedTabs as is, inheriting from UnderlinedTabsBase, and create a MaterialUnderlinedTabs. This MaterialUnderlinedTabs will have a geometryImage and a classic image and the GeometryImage would take precedence over Image as you suggested :)

Also, would you be interested in. making a blog post about your PR in sharpnado ?

**Comment by mkanyo** [comment]
Yes, great, thanks for the comments - I agree with all the above 🤓 

I'm a little busy at the moment but I hope I can pick this up early next week.

Well, once it's done I'd be honored to do a post on it ... but let me focus first at the tasks at hand 😉

**Comment by mkanyo** [comment]
Hello @roubachof 

I have made the changes so now the values for IconOptions are:

-  LeadingIcon
-  TopIcon
-  IconOnly
-  TextOnly

And now there's only 1 tab iten called `MaterialUnderlinedTabItem` which has both an `IconImageSource` and a `GeometryIcon` property of types `ImageSource` and `Geometry` respectively - if GeometyIcon is set then that is preferred by default over ImageSource.

There are additional properties that go with each i.e. `Fill`, `StrokeThickness` for **GeometryIcon** based icons and `IconSize` for `IconImageSource` based icons.

**IconImageSource** based variations look like this:

`LeadingIcon`:
image
`TopIcon`:
image
`IconOnly`:
image
`TextOnly`
image

Code like this for example (`LeadingIcon`):
image

**GeometryIcon** based variatios look like this:
`LeadingIcon`
image
`TopIcon`
image
`IconOnly`
image
'TextOnly'
image

Code like this for example (`LeadingIcon`):
image

I tried to make the spacing balanced however I think ultimately it all depends on the Height of the parent TabHostView. As that expands it can allocate too much space for the child items, similarly if the TabHostView has too little height tab items will not fit. I don't think that this is an issue because if you want to have your tab in a certain way you need to have the appropriate amount of space available for the parent (and the child tabs) but let me know what you think.

For example if you have your TabHostView with too little space it will squash the items (for demonstration purposes the TabHostView control is light pink here):
image

Similarly if it has too much space it can also look strange:
image

Again... I am obviously biased but I think these are edge cases because you should be able to control your TabHostView to meet your design requirements normally. 😀

Cheers,
Miklos

**Comment by roubachof** [comment]
ok let's see this PR :)

**Comment by roubachof** [comment]
why this change ?

image

**Comment by mkanyo** [comment]
I noticed that on iOS 14.6 the tab switching was not working anymore - not just with the MaterialIconTabs but with the original UnderlinedTabItems either. Sorry, I should have made a note on that.

**Comment by roubachof** [comment]
I couldn't replicate the tab switching bug on iOS 14.6 so I re-enabled it.
I merged your PR, and fixed some spacing issues to have a clean result with all kind of TabHost height.
I also added a IconTextSpacing to really fine tune your tab if you have any spacing issues.
I updated the readme, you can add some information about the Geometry icon if you like, for now it's really basic...

**Comment by roubachof** [comment]
the package is ready now.
So if you still want to write a post on sharpnado you are more than welcome :)
If you want to proceed, I just need a markdown with images/gifs in a compressed folder.
If you want ideas on how to structure the post, here is what could be a plan

1. who are you
2. why did you use sharpnado tabs?
3. why you had this idea?
4. first implementation
5. communication on the PR
6. final adjustments

It could be small amount of text for each points, or long ones, it's up to you !

You can also come up with a totally different plan, it's fine by me :)

let me know what you think

**Comment by roubachof** [comment]
oh and it would be cool if you could validate the package with your sample (find it attached)
I validated iOS and Android with the silly app.
[Sharpnado.Tabs.2.2.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Tabs/files/6793486/Sharpnado.Tabs.2.2.0.nupkg.zip)

**Comment by roubachof** [comment]
Oh and great job :)
I didn't have much adjustments to make

**Comment by roubachof** [comment]
If you don't really have time or just the desire to write a post, you can just answers the question here, and I will just turn them into an interview in a blog post :)

**Comment by mkanyo** [comment]
Hey, I’m sorry for the delay but my baby girl was born 3 weeks ago 🥂 and it feels it’s been one very very long day since then… At the very least I’ll try to answer your questions next week but hopefully I’ll soon get to test it properly too and perhaps help with the post. But I’ll aim at the questions in the first round! 

Cheers, Miklos

Az iPhone-omról küldve

**Comment by roubachof** [comment]
Wow that's a great news!
Congrats !! 🎉 🎈 🍾 
I wish you and your family happiness and especially joy.
But also courage, cause having a child is very demanding in the first years :)
So no worries of course, take your time.

If you want to look at this issue, it could be good.
I think it is due to the fact I tried to keep the XF version as low as possible, so it is set to 4.8 but maybe there have been some api changes between 4.8 and 5.0?
https://github.com/roubachof/Sharpnado.Tabs/issues/40

happy baby !
JM.

**Comment by mkanyo** [comment]
Well, I'm sorry for the delay! And thanks for the good wishes - yes quite demanding and exciting times 😄 !!

I had a look at nuget you attached and the latest code on master as I also ran into issue #40 

I think it's because in the final version of the code you also removed a SolidColorBrush instantiation here:
https://github.com/roubachof/Sharpnado.Tabs/blob/eb0c563f5fdc3f2b702b2db6ff0b962b1a13f6ae/Tabs/Tabs/MaterialUnderlinedTabItem.xaml.cs#L179

It was originally meant to be this:
`var brush = new SolidColorBrush(IsSelected ? SelectedTabColor : UnselectedLabelColor);`

I'm not entirely sure how this compiled correctly but I ILSpied the dll in nuget 2.2.0 and this is how this compiled as:
image

I guess this is why it's throwing a missing method exception at runtime.

I checked out the latest master, changed that one line and referencing the project it loads. 

image

Do you want me to send a pull request targeting the issue or can you change it in master directly perhaps?

Cheers,
Miklos

**Comment by mkanyo** [comment]
Also, I finished with the summary for the story behind this PR as per your points above. 🎤 🤓  I can post it here or can drop it over in an email or on Twitter or whatever. 🙂

**Comment by roubachof** [comment]
Great! The world will be dazzled :)
I will change this line no worries !
You can send me an email to jm@sharpnado.com

**Pull request merged**
